package com.curio.curioapp.curioappbackend.service;


import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Service;


import com.curio.curioapp.curioappbackend.dto.AddToInquiredItemsRequest;
import com.curio.curioapp.curioappbackend.dto.CoordinatesDto;
import com.curio.curioapp.curioappbackend.dto.InquiryRequest;
import com.curio.curioapp.curioappbackend.dto.InquiryResponse;
import com.curio.curioapp.curioappbackend.dto.ItemDto;
import com.curio.curioapp.curioappbackend.dto.StatsDto;
import com.curio.curioapp.curioappbackend.model.Inquiry;
import com.curio.curioapp.curioappbackend.model.Item;
import com.curio.curioapp.curioappbackend.repository.InquiryRepository;
import com.curio.curioapp.curioappbackend.repository.ItemRepository;
import com.curio.curioapp.curioappbackend.repository.UserRepository;
@Service
public class ItemService {
	
	@Autowired
	private UserRepository userRepository;
	@Autowired
	private AuthService authservice;
	@Autowired
	private ItemRepository itemRepository;
	@Autowired
	private InquiryRepository inquiryRepository;
	
	
	public void postItem(ItemDto itemDto) {
		Item item = new Item();
		User username = authservice.getCurrentUser().orElseThrow(()->
				new IllegalArgumentException("No user logged in"));
		
		
		if (username!=null) {
			item.setItemId(itemDto.getItemId());
			item.setItemName(itemDto.getItemName());
			item.setType(itemDto.getType());
			item.setPostedTimeStamp(itemDto.getPostedTimeStamp());
			item.setDescription(itemDto.getDescription());
			item.setQuality(itemDto.getQuality());
			byte[] decodedByte = Base64.getEncoder().encode(itemDto.getPhoto().getBytes());
			item.setPhoto(decodedByte);
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get(); 
			item.setPostedUser(user);
			
			if(itemDto.getSale().equalsIgnoreCase("true")) {
				item.setSale("Sale");
			}
			if(!itemDto.getSale().equalsIgnoreCase("true")) {
				item.setSale("");
			}
			
			if(itemDto.getDonation().equalsIgnoreCase("true")) {
				item.setDonation("Donation");
			}
			if(!itemDto.getDonation().equalsIgnoreCase("true")) {
				item.setDonation("");
			}
			if(itemDto.getExchange().equalsIgnoreCase("true")) {
				item.setExchange("Exchange");
			}
			if(!itemDto.getExchange().equalsIgnoreCase("true")) {
				item.setExchange("");
			}
			if(itemDto.getRenting().equalsIgnoreCase("true")) {
				item.setRenting("Renting");
			}
			if(!itemDto.getRenting().equalsIgnoreCase("true")) {
				item.setRenting("");
			}
			item.setSoldFlag("Available");
			
			itemRepository.save(item);
			
		}
				
		
	}
	
	public List<ItemDto> showAllItems(int distanceValue){
		List<Item> items = itemRepository.findAll();
		List<Item> sendingItemList = new ArrayList<>();
		List<Item> sendToClient = new ArrayList<>();
		System.out.println(distanceValue);
		double d=0;

		User username = authservice.getCurrentUser().orElseThrow(()->
		new IllegalArgumentException("No user logged in"));

		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get();
			
			if((user.getLatitude()==0 || user.getLongitude()==0) && distanceValue < 100) {
				for(Item i:items) {
					if((!user.getInquiredItems().contains(i) && !i.getPostedUser().equals(user))) {
						sendingItemList.add(i);
					}
				}
			}
			else if(distanceValue>=100) {
				for(Item i:items) {
					if(!user.getInquiredItems().contains(i) && !i.getPostedUser().equals(user)) {
						sendingItemList.add(i);
					}
				}
			}else if(distanceValue<100) {
				for(Item i:items) {
					double longitudeC=user.getLongitude();
					double latitudeC=user.getLatitude();
					double longitudeP=i.getPostedUser().getLongitude();
					double latitudeP=i.getPostedUser().getLatitude();
					
					d=distance(longitudeC,latitudeC,longitudeP,latitudeP);
					System.out.println(d);
				
					if(!user.getInquiredItems().contains(i) && !i.getPostedUser().equals(user) &&  d <= distanceValue) {
						sendingItemList.add(i);
					}
				}
		
			}
		}
		for(Item i:sendingItemList) {
			if(!i.getType().equals("This items is not available") && i.getSoldFlag().equals("Available")) {
				sendToClient.add(i);
			}
		}
		return sendToClient.stream().map(this::mapFromItemToDto).collect(Collectors.toList());
	}
	
	
	public List<ItemDto> getItemInfo(long itemId){
		 System.out.println(itemId);
		 com.curio.curioapp.curioappbackend.model.User user= getCurrentlyLoggedInUser();
		 List<Item> items=new ArrayList<>();
		 Item item=null;
		 if(user!=null) {
			 item = itemRepository.findById(itemId).get();
			 items.add(0, item);
		 }
		 
		 long i=1;
		 while(i<5) {
			 Optional<Item> nextItem= itemRepository.findById(item.getItemId()+i);
			 if(nextItem.isPresent()) {
				Item retrived=(Item)nextItem.get(); 
				if(retrived.getType().equalsIgnoreCase(item.getType()) && (!retrived.getPostedUser().equals(user)) && !user.getInquiredItems().contains(retrived) && (!retrived.getType().equalsIgnoreCase("This items is not available")) && retrived.getSoldFlag().equalsIgnoreCase("Available")) {
				 items.add(retrived);
				}
				
			 }
			 i++;
		 }
		 return items.stream().map(this::mapFromItemToDto).collect(Collectors.toList());
	}
	
	
	public List<ItemDto> showMyItems(){
		User username = authservice.getCurrentUser().orElseThrow(()->
				new IllegalArgumentException("No user logged in"));
		List<Item> myItems = null;
		List<Item> sendingItemsList=new ArrayList<>();
		
		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get();
		    myItems = itemRepository.findByPostedUser(user);
		    for(Item i:myItems) {
		    	if(!i.getType().equals("This items is not available")) {
		    		sendingItemsList.add(i);
		    	}
		    }
		}		
		return sendingItemsList.stream().map(this::mapFromItemToDto).collect(Collectors.toList());
	}
	
	public boolean addToInquiredItems(AddToInquiredItemsRequest addToInquiredItemsRequest) {
		
		boolean added = false;
		User username = authservice.getCurrentUser().orElseThrow(()->
				new IllegalArgumentException("No user logged in"));
		
		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get();
			
			Optional<Item> optionalItem = itemRepository.findById(addToInquiredItemsRequest.getItemId());
			
			if(optionalItem!=null) {
				Item item = optionalItem.get();
				if (!item.getPostedUser().equals(user) && !user.getInquiredItems().contains(item)) {
					Item addInquiredItem = new Item();
					addInquiredItem.setItemId(addToInquiredItemsRequest.getItemId());
					addInquiredItem.setItemName(item.getItemName());
					addInquiredItem.setType(item.getType());
					addInquiredItem.setPostedTimeStamp(item.getPostedTimeStamp());
					addInquiredItem.setDescription(item.getDescription());
					user.getInquiredItems().add(item);
					userRepository.save(user);
					added = true;
				}
			}	
		}
		return added;	
	}
	
	public List<ItemDto> showMyWishlist(){
		
		User username = authservice.getCurrentUser().orElseThrow(()->
				new IllegalArgumentException("No user logged in"));
		List<Item> myWishlist = null;
		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get();
			myWishlist = user.getInquiredItems();
		}		
		return myWishlist.stream().map(this::mapFromItemToDto).collect(Collectors.toList());
		
	}
	
	public List<InquiryResponse> getInquiries(long itemId){

		List<Inquiry> sendingInquiries = new ArrayList<>();
		User username = authservice.getCurrentUser().orElseThrow(()->
		new IllegalArgumentException("No user logged in"));
		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get();
			
			
			Optional<Item> itemFound = itemRepository.findById(itemId);
			Item inquiredItem = itemFound.get();
			if(inquiredItem!= null) {
				List<Inquiry> inquiries = inquiryRepository.findByInquiredItem(inquiredItem);
				for(Inquiry i: inquiries) {
					if(i.getSentBy().equals(user) || i.getReceivedBy().equals(user)) {
						sendingInquiries.add(i);
					}
				}
			}
		}
		
		
		return sendingInquiries.stream().map(this::mapFromInquiryToDto).collect(Collectors.toList());
		
	}
	
	
	public boolean makeInquiry(InquiryRequest inquiryRequest) {
	
		boolean made=false;
		User username = authservice.getCurrentUser().orElseThrow(()->
		new IllegalArgumentException("No user logged in"));
		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get();
			
			Optional<Item> itemFound = itemRepository.findById(inquiryRequest.getItemId());
			Item inquiredItem = itemFound.get();
			if(inquiredItem!=null) {
				Inquiry inquiry=new Inquiry();
				inquiry.setSentBy(user);
				inquiry.setReceivedBy(inquiredItem.getPostedUser());
				inquiry.setInquiredItem(inquiredItem);
				inquiry.setMessageContent(inquiryRequest.getMessage());
				inquiry.setInquiredTimeStamp(inquiryRequest.getTimeStamp());
				inquiryRepository.save(inquiry);
				made=true;
			}
			
			
		}
		return made;
	}
	
	public boolean reply(InquiryRequest inquiryRequest) {
		boolean made=false;
		
		User username = authservice.getCurrentUser().orElseThrow(()->
		new IllegalArgumentException("No user logged in"));
		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			com.curio.curioapp.curioappbackend.model.User user= optionalUser.get();
			
			Optional<Item> itemFound = itemRepository.findById(inquiryRequest.getItemId());
			Item inquiredItem = itemFound.get();
			
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalToUser = userRepository.findByUsername(inquiryRequest.getTo());
			com.curio.curioapp.curioappbackend.model.User toUser= optionalToUser.get();
			if(inquiredItem!=null) {
				Inquiry inquiry = new Inquiry();
				inquiry.setInquiredItem(inquiredItem);
				inquiry.setSentBy(user);
				inquiry.setReceivedBy(toUser);
				inquiry.setMessageContent(inquiryRequest.getMessage());
				inquiry.setInquiredTimeStamp(inquiryRequest.getTimeStamp());
				
				inquiryRepository.save(inquiry);
				made=true;
				
				
			}
			
		}
		return made;
	}
	
	public Boolean removeInquiry(long inquiryId) {
		 boolean removed=false;
		 com.curio.curioapp.curioappbackend.model.User user= getCurrentlyLoggedInUser();
		 
		 if(user!=null ) {
			Optional<Inquiry> inquiryFound = inquiryRepository.findById(inquiryId);
			if(inquiryFound.isPresent()) {
				Inquiry inquiry=inquiryFound.get();
				if(inquiry.getSentBy().getUserId()==user.getUserId()) {
				
					inquiryRepository.deleteById(inquiryId);
					removed=true;
				}
				
			}
			else if(!inquiryFound.isPresent()) {
				removed=true;
			}
			
		 }
		
		 return removed;
	}
	
	
	 public Boolean removeFromWishlist(long itemId) {
		 boolean removed=false;
		 com.curio.curioapp.curioappbackend.model.User user= getCurrentlyLoggedInUser();
		 Optional<Item> itemFound = itemRepository.findById(itemId);
		 Item item = itemFound.get();
		 if(item!=null && user!=null) {
			 if(user.getInquiredItems().contains(item)) {
				 List<Item> inquiredItems=user.getInquiredItems();
				 removed = user.getInquiredItems().remove(item);
				 user.setInquiredItems(inquiredItems);
				 userRepository.save(user);
				 
			 }
		 }
		 
		 return removed;
	 }
	 
	 public boolean removeFromMyItems(long itemId) {
		 boolean removed=false;
		 com.curio.curioapp.curioappbackend.model.User user= getCurrentlyLoggedInUser();
		 Optional<Item> itemFound = itemRepository.findById(itemId);
		 Item item = itemFound.get();
		 if(item!=null && user!=null) {
			 
			 item.setDescription("");
			 item.setQuality("");
			 item.setDonation("");
			 item.setExchange("");
			 item.setRenting("");
			 item.setSale("");
			 byte[] decodedByte = Base64.getEncoder().encode("iVBORw0KGgoAAAANSUhEUgAAB1gAAAYoCAYAAAAwXB1MAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAOxAAADsQBlSsOGwAAIABJREFUeJzs2UENwDAQwLC2gI4/uxXC8psm2Qjyz56ZZwEAAAAAAADw6nwdAAAAAAAAAPAXBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAAEQGKwAAAAAAAEBksAIAAAAAAABEBisAAAAAAABAZLACAAAAAAAARAYrAAAAAAAAQGSwAgAAAAAAcNm7966oDnzPw7+6UAjeUBSDETSIJkaDJp3k9JoXcNa831nnBcw6s86cTifmYnvpZDTeAYWooAUIVM0fvfqSBOQntYuNxfP8GWrv/V1GdG0/1C4gSWAFAAAAAAAASBJYAQAAAAAAAJIEVgAAAAAAAIAkgRUAAAAAAAAgSWAFAAAAAAAASBJYAQAAAAAAAJIEVgAAAAAAAIAkgRUAAAAAAAAgSWAFAAAAAAAASBJYAQAAAAAAAJLqZQ8AAACAiIh6vR71ej2qlcqv/nur3Y7V1dVYX18vaRkAAAD8k8AKAABAKer1eoyPjcXx48fj2PBw1OtvvkV9/fp1zM3Px+zsbDyeno61tbUdWgoAAAD/VJmammqXPQIAAIC9Y3h4OM6Mj8fo6GjUarVtnWNtbS0ePnoUP9+9GwsLCwUvBAAAgM0JrAAAAOyIw4cPx6WPP45jx44Vet7H09Nx48aNeNVsFnpeAAAA2IhHBAMAANB15yYn48JHH0XlN5+vWoSTo6NxYmQkfrh2Le4/eFD4+QEAAOBfCawAAAB0Tb1ej88/+yxOnDjR1evUarX49MqVGD56NL6/di1arVZXrwcAAMDeVS17AAAAAL2pUqnElcuXux5X/9X4+Hh8fOHCjl0PAACAvUdgBQAAoCsuXbwY7588uePXPTsxEecmJ3f8ugAAAOwNAisAAACF+/D8+Zj44IPSrv/xhQtx6v33S7s+AAAAvUtgBQAAoFAnRkbiw/Pny54RVy5fjsOHD5c9AwAAgB4jsAIAAFCYer0eU1NTUalUyp4StVotrkxNlT0DAACAHiOwAgAAUJhzk5MxODBQ9ox/GBoaijOnT5c9AwAAgB4isAIAAFCIarW6K2PmByV+FiwAAAC9R2AFAACgEONjY9FoNMqe8TuHDh6MkZGRsmcAAADQIwRWAAAACrEb3736d7t5GwAAAO8WgRUAAICODQ0NxeHDh8uesakTIyMxsG9f2TMAAADoAQIrAAAAHTt65EjZE96oWq3GwUOHyp4BAABADxBYAQAA6NhuD6wREUO7+B22AAAAvDsEVgAAADp24MCBsidsaXBgoOwJAAAA9ACBFQAAgI4NDg6WPWFLAwIrAAAABRBYAQAA6FhfX1/ZE7bUaDTKngAAAEAPEFgBAADYE2q1WtkTAAAA6AECKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAMCesL6+XvYEAAAAeoDACgAAwJ7QbrfLngAAAEAPEFgBAADo2PLyctkTtrS8slL2BAAAAHqAwAoAAEDHXr58WfaELTWbzbInAAAA0AMEVgAAADr2YmGh7AlbWlhcLHsCAAAAPUBgBQAAoGNzc3NlT9jSs2fPyp4AAABADxBYAQAA6Njc/HzZE95oeXk5Fr2DFQAAgAIIrAAAAHRsbW0tpmdmyp6xqUePH5c9AQAAgB4hsAIAAFCIO3fulD1hU/cfPCh7AgAAAD1CYAUAAKAQc/Pzu/KzWB8+ehQLCwtlzwAAAKBHCKwAAAAU5vqNG2VP+JX19fX4648/lj0DAACAHiKwAgAAUJjnL17Eg130ON7/d/t2vHz5suwZAAAA9BCBFQAAgEJdu349lpaWyp4RCwsL8eNPP5U9AwAAgB4jsAIAAFCo1dXVuPrdd6VuWFtbiz9/8020Wq1SdwAAANB7BFYAAAAKNzc3F99cvVrKtdvtdvzpz3/2aGAAAAC6ol72AAAAAHrTw0ePYn19Pf7w2WdRq9V25Jpra2vx1ddfx9zc3I5cDwAAgL3HO1gBAADomumZmfg///Vf0Ww2u36thYWF+N//+Z/x9OnTrl8LAACAvasyNTXVLnsEAAAAva3RaMTlqak4OTralfPfvXs3rl2/7jNXAQAA6DqBFQAAgB1z7NixuHjhQgwNDRVyvrm5ufjLjRvx4sWLQs4HAAAAWxFYAQAA2HGnTp2KiTNn4siRI9s6/uncXNy+fTtmnzwpeBkAAAC8mcAKAABAaQ4ePBgnRkZieHg49u/fH4MDA1Gr1X71mrW1tVhaWorFly9jbm4uZmdno7m0VNJiAAAA9jqBFQAAgF2lv78/Bvbti1a7HcvLy/H69euyJwEAAMA/1MseAAAAAP9qZWUlVlZWyp4BAAAAG6qWPQAAAAAAAADgXSGwAgAAAAAAACQJrAAAAAAAAABJAisAAAAAAABAksAKAAAAAAAAkCSwAgAAAAAAACQJrAAAAAAAAABJAisAAAAAAABAksAKAAAAAAAAkCSwAgAAAAAAACQJrAAAAAAAAAAwNzKfAAAgAElEQVRJAisAAAAAAABAUr3sAQAAAHDwwIE4eOhQDA4MxMDAQAwODkar1YqlpaVYWlqKZrMZCwsL8arZLHsqAAAAe5zACgAAwI5rNBpxcnQ0hoeH49jwcOzbty91XLPZjKdzc/HLL7/E4+npWFtb6/JSAAAA+LXK1NRUu+wRAAAA7A3VajXOTU7G2YmJ6Ovr6+hcKysrceuvf4179+9Hu+3WFgAAgJ0hsAIAANB1lUolxk6dio8++igGku9WzVp8+TJu3rwZ0zMzhZ4XAAAANlItewAAAAC979LFi/HplSuFx9WIv31+6xeffx5nJyYKPzcAAAD8ls9gBQAAoGtqtVp8+fnnMTIy0tXrVCqVuHTxYhw6eDC+/f77rl4LAACAvU1gBQAAoCv27dsX//bFFzE0NLRj1xwfH4/+/v74+urVWFtb27HrAgAAsHd4RDAAAACFq1Qq8enlyzsaV//uxIkT8fGFCzt+XQAAAPYGgRUAAIDCffThh11/LPCbfHDmTJw5fbq06wMAANC7BFYAAAAKdXp8PM6fO1f2jPjk0qU4UWLkBQAAoDcJrAAAABSmv78/Ln78cdkzIiKiWq3G5ampqFbd+gIAAFAcd5kAAAAU5tzkZPT19ZU94x8GBgY8KhgAAIBCCawAAAAUor+/f1fGzMmzZ72LFQAAgMK4wwQAAKAQH54/H7VarewZvzMwMBBnJybKngEAAECPEFgBAAAoxMnR0bInbGr0vffKngAAAECPEFgBAADo2PDwcPT395c9Y1NDQ0MxODBQ9gwAAAB6gMAKAABAx0aOHy97whtVKpU4Ojxc9gwAAAB6gMAKAABAxwYHB8uesKX978BGAAAAdj+BFQAAgI4dOXKk7AlbOnz4cNkTAAAA6AECKwAAAB3bt4s/f/Xv3oWNAAAA7H4CKwAAAB2r1WplT9hSpVIpewIAAAA9QGAFAABgT+hrNMqeAAAAQA8QWAEAAOjY69evy56wpVcvX5Y9AQAAgB4gsAIAANCxlXcgsL4LERgAAIDdT2AFAACgYyvLy2VP2NK7EIEBAADY/QRWAAAAOvbLs2dlT9jS4uJi2RMAAADoAQIrAAAAHXvy9GnZE7Y0NzdX9gQAAAB6gMAKAABAx549exarq6tlz9jU4suX8arZLHsGAAAAPUBgBQAAoGOtVivm5ufLnrGpJ0+elD0BAACAHiGwAgAAUIjdHDHfhUcYAwAA8G4QWAEAACjE3Xv3Yv6XX8qe8TvTMzO7Ov4CAADwbhFYAQAAKMzNW7fKnvAr7XZ7120CAADg3SawAgAAUJj5+fmYnZ0te8Y/PHj4MBYXF8ueAQAAQA8RWAEAACjUD9euxerqatkzotlsxo2bN8ueAQAAQI8RWAEAAChUc2kprn77bbTb7dI2rK+vx1dffx0rKyulbQAAAKA3CawAAAAUbmZ2Nv7644+lXf/7H36IFy9elHZ9AAAAepfACgAAQFf8+NNPMTMzs+PX/fnu3Xjw8OGOXxcAAIC9oTI1NVXeM5sAAADoeWdOn46pTz6JSqXS1eusr6/HN1evxnQJURcAAIC9o172AAAAAHrb3Xv34lWzGX/49NPo7+/vyjWazWZ89fXXHgsMAABA13kHKwAAADui0WjE2YmJmPjgg6jXi/l539XV1bh9507cvnMn1tbWCjknAAAAvInACgAAwI5qNBpxbnIyxsfGotFobOscy8vLcffevbjz88+xurpa8EIAAADYnMAKAABAaYaHh2P0vfdidHQ0BgcG3vjaxcXFmJ6ZiemZmXj+/PkOLQQAAIBfE1gBAADYFSqVStRqtahWq1Gr1SLa7VhvtaLVasX6+nq0225fAQAAKF8xH3oDAAAAHWq32z5HFQAAgF2vWvYAAAAAAAAAgHeFwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAECSwAoAAAAAAACQJLACAAAAAAAAJAmsAAAAAAAAAEkCKwAAAAAAAEBSvewBAOw+tVot/ue///u2jn08PR3ffvddwYvKVa1W4+TJkzFy/HgcPnQo+vr6ol6vx+rqaiwvL8ez58/j0ePH8ezZs7Kn7ln9/f0xdupUHD16NA4cOBB99XpUq9VYXV2Nl69exbNnz+LBw4fRbDbLngoU5MCBAzF26lQcGRqKwcHB6Ovri3a7Ha9XV2NxcTGePn0ajx4/jtXV1bKnAsA7Zyfvgdx/7oyRkZH44g9/2Nax165fj/v37xe8aGf4/QVAtwisAGyoXt/eXxHVam89HOH48ePx6eXLMTAw8Luv9fX1xeDgYBw9ejTOTkzEkydP4up338XKykoJS/eusxMTceGjj6JWq/3ua41GI/bv3x8nRkbiw/Pn487PP8f1Gzei3W6XsBQoQq1Wi6lPPonxsbENv97f3x8HDxyIk6Oj8fGFC3Ht+vV48ODBDq8EgHdXGfdA7j+7rxId/DpXKsWO2WF+fwHQDf6WAIBNHDt2LP745Zcb/sPCRkZGRuJ//PGP27554+2dP3cuLl28uGFc/a1KpRJnJybi0ytXdmAZ0C1ffP75pnH1t/r6+uKzK1difHy8y6sAoDe4BwIAyBFYAWADlUolLk9NvfVPrB46dCjOTU52aRX/av/gYHx4/vxbHzd26lSMjIx0YRHQbWNjY3FiG9+/n1y8GI1GowuLAKB3uAcCAMjz42UAbzD63nuxb9++smcUam5+PhYXF8uesesdP3YsDuzfv61jz5w+HTdv3Sp4Eb81Pj6+7Uc2nR4fjydPnhS8COi2M6dPb+u4er0ep95/P+78/HPBiwCgd7gHAgDIE1gB3uDc5GQcOXKk7BmF+v6HHwTWhKNHj2772EajEQcPHvTr3GXDHfw/6uRYoBzVajWGDh/e9vHDw8MCKwC8gXsgAIA8jwgGgA10+s7lff39BS1hM/uSnwu1kf7+/qhUKgWuAbqtv9HY9rvWI/72fQ8AbM49EABAnsAKABuo1WqlHs/Wqh0G0k5CDbDzOv5z2fc8ALyReyAAgDz/ygAAG3j9+nVHx6+srBS0hM2srq5u+9hWqxXr6+sFrgG67XUH3/MRESsd/rkOAL3OPRAAQJ7PYAWADSwsLGz72FarFQs+e6jrFhYX49ChQ9s69vnz5wWv+Zv9+/fHoYMHt3zd9MxMV64Pvez169extLQUA9t8PHi3vu+BN3vvxIktH8u/uLgYL1+92qFFwGbcAwEA5AmsALCB2SdPotVqbesxsk+ePvXuyB0wMzsbp95/f1vHPp6eLnjN33xy6VKcGBl542tarVb8r//4j65cH3rd7OxsnDlzZlvHTnfp+x7Y3JGhofi3L7/c8nU3b92KH3/6aQcWAW/iHggAIM8jggFgA8vLy3Hv/v23Pq7VasXNW7e6sIjfevTo0bZ+yv5Vsxl3790rfE9/f38cP3as8PMC//TT7duxtrb21sc9evQoXnTwrhxge8bGxsqeALwF90AAAHkCKwBs4tpf/hJPnj5Nv359fT2ufvttR4/W4u386auvotlspl+/tLwcf/rqq678dP3YqVPb+ml/IK/ZbMY3V6++VWSdn5+Pb7//vourgI1UKpV4/+TJsmcAb8k9EABAjkcEA8Am2u12/N///u/44MyZ+P/s3edjE1m2LvynSjnLkizJtpwNtgGTabqB7pnpM+fcc897/+J755zpSA5NBucoK9nKWap6Pxh7DG1AqipFP78vTYOraluhwl57rTU1NQW7zfbZn4tEo3j3/j0nFtqsUCzinz//jNmzZzE+NgaDwXDiz9VqNWxubeH94iIqlUpLxjIaCrVkv0T0sUg0ip9/+QVzc3MYCgY/u7ChUCxidXUVq2trkGW5zaMkomAwCKPR2OlhEFGT+AxERERE1BgGWImIiL5ibX0dq2trsNvtcDqdMBmNEEURtVoNhWIRqVRKUclK0katVsPrN2/w5u1bOB0O2B0OGPR6CIKAaq2GfC6HVDrd0gCLy+WC0+ls2f6J6GO5fB6PnzyBTqeD2+WC1WqFwWCAJEmoVKvIZDLIZrMQBKHTQyU6tca48Iiop/EZiIiIiOjLGGAlIiJt9WmWkCAIyOfzyOfznR4KfYYsy0hnMh3pszjGHnNEHVGv17G3v4+9/f0//RuDq0SdYzQa4ff7Oz0MIlKJz0BEREREn8dGYUREpCmWYaTThj3miIiIPsa+5ERERERE1O+YwUpE9AW//PabZvu6dvUqQiMjira99+ABYrGYZmNppVq93ukhELVVMBCAyWTq9DCIiIi6Bis7EBH1Fy6kJiIi+jMuKSUiIk1JktTpIRC11SgnkYmIiI6wLzkRUf9hgJWIiOjPGGAlIiJN1Wq1Tg+BqG2MRiMC7DFHRER0ZDQU6vQQiIhIY1xITURE9GcsEUxERJqqN1gi2Gq1wufzwWG3w26zwWQyQafTQafToV6vo16vo1ypoFgsIpPJIJ1OI5VOc+XsB4IgHGWI2KxWWK1WGI1GGA0GiKIIUacDAEj1OiRJQrlcPno984UCctksMtlsw+8XnSw0MtK3PeZEUYTb7Ybb5YL1w2fMZDQefU9lHHy+avU6yuUyCoUC8vk80uk00plMX03C6HQ6DPp8cDqdcDgcMJvNMOj10On1kD6cr2r1OvL5PAqFAjKZDPb29zVfcGK32+H1eOBwOGC32WAwGqHX6yGK4tF7USqVDs6b2SxSqRTS6TQEQdB0HPR5ZrMZLqcTdrsdNpsNZrMZRqMRhg/vkyCKkCTp4P2q1VAql1GpVJDP55HL5ZDNZlEoFjv9a3Q1k8n0r++B3Q6L2Qy9Xg/dh+terVZDtVpFqVRCvlBAKpXCfjKJarXa4ZE3xmg0YsDthsPhgNVqhcVigdFohE4UD869soxqrYZatYpqrXZw3s1kkMlkkMvlOj189iVXwWw2w+1ywWazwWazwWI2w2gywWQyQa/TQRCEg/O9JB19Dsrl8sFn/cM5JJlKIZvN8rzfBex2O5xOJ+wf3k+TyQST0QijyQRREKD78J5KkgRJklCpVg/u10slZHM55HI57O/vo1Qud/pXoU+Ionh0rbfb7Qf3yB/eX8OHZ7HDa1K9Xocky6iUyyiVyygVi8jmcshks0gmkz21OLmR50ZBEODxeOAZGDi4F7JaD67RH+6ZD+9Vsx/uU+OJBJ9Hv8BisRy9llarFRaz+eAzptNBJ4oH8yaShOqH5/xiqYRMJoNkKoVSqdTp4RMRnQoMsBIRkaa+NIFpMpkwPjaG0VAIdrtd0b6jsRg2NjeRSCTUDPOrdDod/vqXvyjaNhqN4tXr1xqP6OABa3hoCMFAAB6PR3VgT5Ik5HI57O3vI55IIB6P99RDvs/rxaVLlxRt++79e+zs7Kg6/tTkJOZmZ5veThRF/NuPPyo+7k8//9yyiQiz2YzhoSEMDQ3BMzCg+DMmSRISiQR2IxHsRiIot3hysNnv6/Pnz5HY2/vqzwUDAUyMj8Pn8x1NlH3JoM939GdJkpBKpbC5tYXtnR3F75nNasX4+DhGhodhtVqb3r5UKmE3EsHG5ibS6bSiMXSTMzMzGBsbU7TtvXv3NA9eCoIA/+AghoJB+P1+WCwW1fusVCpIJpOIJxJI7O313Pt24/r1hsvDbm1tYXFp6as/ZzQaMTY6itDICJxOZ9PBI0mSkEwmsb2zg63t7a6bzPV6PBgaGkIgEIDdZlO8n0qlgkg0inA4jHgi0faFLjabDZcWFmA2m5vednpqSnHJ/c3NTSwtLyvatpNsNhv8g4MYHByEZ2Cg6X7uJpPpxM9LuVxGPB7HTjiMaCymyeJEv9+PhQsXFG0r1ev4+ddfW/55vHPrFkwKPnsAsLS8jM3NTVXHd7vdB++nzwe32w29vrnpNrPZDDgcf/r7fD6PSDSKnXAYyWRS1Rgb0Y3PQJ2m0+ng9XgwODgIn9cLp9PZ8D3y4efAYjbD9cm/ybKMdDqN8O4uwuEw8oWCxiPXVu0L106n04npyUkEg0EYjcav72xoCMDB9TkWj2NtfR2xWEyrofY0n8+HkeFhBFTeVxYKBexGIohEIognElx4Q0TUIgywEhGRpk6atNTpdDh75gxmpqdVBQUNBgNCIyMIjYwgnU7jzdu3iMXjaob7RUonOVNNTpB9jdfrxZmZGfgHBzV9MBJFEU6nE06nE5MTE5AkCXv7+wiHw9je2en6YKtOp1P8HhmanPQ6bsDtxsWFBbjdbsX7UDOBLn5Yrawlt8uFmZkZDA8NafIZE0URfr8ffr8fF86fRzgcxtLKCrLZrAajPVkzr2kwGPxigHV4aAjn5udhU/k+eTweeDwenD93DkvLy1heWWl4ottqteL8uXMYCgZVvSdmsxmTExOYnJhANBbD6zdvWvo+tJrBYFD8/dEy29xgMGBqchIT4+OKgklfYjQaEQgEEAgEAADFYhG7kQi2d3baMrmultViafg9Ghke/mKA1WQyYe7sWYyNjal6/0RRhNfrhdfrxfzcHJZXVrCyutrRTHu9Xo+x0VFMTU6qOtccdxiIHhsdRbVaxcrqKlbX1lqevavFfZ7RaGxsUv4EzQYmO8lus2FkZATDw8NwnhBM04LJZEIoFEIoFEKpVML6xgZWVldV3dft7e0dZecpEfD7sRuJKD7+17jdbni9XkXbyrKsOLDj8XgQGhnB8NBQyz6HNpsN01NTmJ6aQiaTwfLKCra2t1tyrEPd8gzUSYIgIBgMHgW6mg2YN3oMt9sNt9uN+bk5xGIxLK2sYK+BRYCdUDvhWmKxWLBw4QKGgkFF+xRFEcFAAMFAAKlUCi9fvcJ+D9zraE2n02F8bAzTU1OKFlSexGq1/uvckc1ibW0NG5ubrAhGRKQxBliJiEhTn07euN1u3Lh+HVYNsnqOc7lc+O7bb7G1vY0XL192fTBQCavFgosLC0eT7K0miiIGfT4M+ny4cP48ItEo1tbXu/Yhv92MRiPm5+YwPjbWNyuAzSYTFhYWMPxhFXkr6HQ6jI6OYmRkBBubm3j3/j0qlUrLjteIgN9/YoaFyWTClcuXNe+razAYcG5+HmOjo3j4+PEXA5yyLOPsmTOYPXu2oazZZgT8fgz6fHi/uIj3i4t98zluJ1mWMTkxgXPz84oDDc2yWCyYmpzE1OQksrkcNjc3sbG52TMlb7/E6XTCbDKdWAJzYnwc58+d03xS22g04tz8PEZDITx++hSZTEbT/TdiYnwc83NzigOKjTAYDJibncXM9DTW1tfxfnGxJZm7wUAAFy5cgE2jCeF+NRQMYnJy8qNKB+1gNpsxNzuLifFxvH3/XnGWZr1ex044jInxcUXbDw8PtzTAquY+JhaPN1VK8zAQMjE+DkeLguSf43Q6cfXKFcxMT+P5y5fY399v6/FPA4vFgsmJCYyNjrZ18YYgCEeLq3YjEbx89QrFLmsZUPnkviMUCuHSwoJm12m3243v79zB0vIy3r57d2oCgaOhEM6fO9fSz5vT4cClixcxNTWF169fI8psYSIizTDASkREmjoeOBkZGcGVS5c0DxIcNxoKweVy4d69e33Vo2hkeBiXL11qyWrpRuh0OowMD2NkeBiRSAQPHj3qyDi6xfjYGM7Nz7d0MrzdxsbGsHD+fNs+Y6IoYnJiAsFAAE+fPWuoRG+rHPbHzOfzR3/ncrnwzY0bmi8G+fS4P9y5g8dPnpw4saHT6XDt6lXFWQCNEEUR83NzcDgcePrs2amZvNKCwWDA9atX4dc4AN8Mh92O8+fOYfbsWdx78KAvJtf9gcBHQR9BEHD1yhWERkZaelyHw3H0fYxEoy091iGbzYbrV6+qqoDQLL1ejzMzMxgaGsIff/yBPY0+M1arFQvnzyPYwvNVPxgdHcWZmRk4FLTG0JLZbMaVS5cwFAziydOnihYmbm5uKg6wBgMB6HS6lgT5ZVlW1fd3c2uroZ/T6/WYnprC1ORkx+8HnU4n7ty6hcWlJbx7/76jY+kXVqsVs2fOIBQKaVrxQomhYBBejwd/PH/e0oUJzTq+sOvc/DzOzMy05DhnZmYw4Hbj/sOHXVfSX0smkwnXrlzB4OBg247psNvx7c2b2NjcxMtXr/r69SUiapfO3jUQEVHfOVzZGgwEcPXy5ZYGVw85HQ7cuX27p0rEfcnM9DSuX7vWseDqp5KpVKeH0DEulwvf37mDy5cudXwyTSuCIODSxYu40qEAvsViwa3vvsPU5GTbj33c8SxVh8OBW99+29Lg6iG9Xo8b16/D4/F89PeCIOCbGzdaGlw9LjQygssKexifRmaTCd/fudPR4Opxh33b+sHx76IgCLh54yuQHIYAACAASURBVEbLg6uHdDodbly/rnnW+klGRkbw1x9+aGtw9Ti7zYbbt25hfm5O1X4EQcDZM2fw41//yuBqA6YmJjoeXD0uGAjge4X3zMlUSnGJeb1e37LvmWdgQHFJzUqlgt3d3YZ+VhRFzExPd839oCAImD17FteuXGFFCg047HbV5ei1ZDQaceP69Y7fLx93GGCdn5trWXD1kM/nw63vvuua52GteTwe/PWHH9oaXD1ufGwMP9y5o3mbCyKi06g77hyIiKhvVCoVOJ1OXL92ra0PqDabDTdv3Oj5CYbxsTGcP3eu08M4IkkSNhSWk+sH5+fn4RkY6PQwNCOKIm7euKE4A0UrgiBg4cIFzM3OdmwMh4Eyg8GA7779tq0TpjqdDjdv3PjomFcuXYK/zZMsY6OjHf8s9AKdTofvvvuuq4Ikm1tbfZN1MOjzHV27r1650ray+IdEUcT1a9dgb+H7OzU5iWtXrnR8ovgwOHrl0iXF90sDAwOYn5trywK6fvB+cbHTQ/gTp9OJW99+q+jz2Gi250lGWrRwQs1+t3d2Gq7kUKlUuvKeOBQK4QoXTKkWjcWQ6rJFpYf3y2NjY50eCqrVKmRZxsT4OM6eOdOWY3oGBnDt6tW2HKud/IODuPXttx0PbjqdTty5fVuznq9ERKcVA6xERKQZWZZRq9Vw7erVjky8DQwMdDRgo5bD4cDChQudHsZHdsJhlPuo9PJpdpgh2e7gxZfMnj3bsZX5Pq8Xoiji0sWLsHRggsNoNOLiwgKAg95xo6OjbR8DAJw/d67jEzzd7tLFi3C2uc/el8iyjPX19U4PQzMGgwEejwfjY2Nty1z9lF6vb1kW2Mz0NBYuXOiqBWBjY2P4pg8WpfWC3UikI31+v+awl2eztra3IUmSomP6Bwc1fz6QZRnDasoDNxkwXV5e7srFLaOjo12V6dirlpaXOz2EE11aWOhY9YNDlUoFDocDF86fb+txg4FATz/ff2rQ58M3N250zSIlm9WK727e7JrMfCKiXsQAKxERaUYQBPzXf/5nRyeiZ6anYevRVZgL5893zcPWobW1tU4PgTSycOFCW8pgNuvC+fMdKbuq0+nw//3v/62qb5taI8PD+D//9V+4fu1ax8ag1+vblonQi7weD0ZDoU4P4yOxeBy5Y/2D+8Gtb7/FpYsXOzoGt9uNcY2zhIaCQZybn9d0n1oJBgJdVTGjXwmC0JVZrMDB57PZa2C5XD6xh3gj9Ho9ghov8vJ6vYoXSaXTaaSbDH6XymVVWbytND8315ZWB/1sJxzuygURoiiqqjygBYvFgu9v3+7Is+qZmRm4XK62H1drdpsNN65f77rnfbvdjm+uX+/0MIiIehYDrEREpKlO960RRRGzZ892dAxKDLjdHevB8jmpVOpU91/tJ6Ojo5icmOj0ME4kCAIuX7wIg8HQ9mN3+nwFHAR6O51FNjY62vHSpd3qTBcGn/tx4Ysoih3/HgDA2TNnNBuH3W7H1S7vjTg9NdV1Cwj6UXh3FxmFvUtb7dz8fNOf0a0uKhOsZpGU0kDp0tKS4izeVtLr9Zjv0gUdvUIQBCwuLXV6GCdyOp0Y61C1E+DgOt2Je/XDY/d6GWxRFPHNjRsdew2/xuv1csElEZFCnZ9VIiIi0tjIyAhMJlOnh9GUbuit86m1PipBeZqZTSZc0ChLKZfLIRKNYnNrCxubm4hEo8jlcqr3a7FY2l5yjP5Fp9N1rDRrNzObzW3vi/s1+UJBcfYYfZ3FYsHQ0JAm+7p6+XJPLFy4dPEi7DZbp4fR97QI2tRqNdRqNQ1G8y9Wq7Xp838kGkWpVFJ0PP/goKbfi6FgUNF2kiRhe2dH0bbFUklVkBk4KG1crVY1D9QODw2xn6JKO+EwsirvbSVJQqVS0fz9nZmZabhncL9xuVw9fa86PzcHhwZVvmq1Gvb29rATDmN9fR074TASe3uaXBtmz56FjfcDRERN6/4nPiIi6kuSJKFWq0GSJBiNRk0zyURRxMjwMFZ7KMtHTYlUSZIQ3t1FJBJBJptFsVhEvV6HKIrQ6/Uwm82wWixwOp3wDAzA6/V+tTRRpVJRPPFE3WVhYUFVX51arYaV1VVsbm6iUCye+DMWiwWjoRBmpqcVr8weDYWwvLKCbBdm+Rz2l5YkCQaDoaOZr5VKBYIgaL4CPhgMYn1jQ9N99jr/4KCq7MNcLoet7W0k9vZQyOdR/fAZ0ul0MBoMsFgscDgccLlcGPT5GprU6qfeq2ocTlwbDAbNS+2NhUIIh8Oq9jE1OYmBgQGNRtRaOp0OFy5cwP0HDzo9lL62s7OD2bNn4bDbv/hzkiQhnU4jlU4jlUohncmgXCqhXKkcBVYEQYDD4YDX48HE+DicTqeqsY2OjmJre7vhn5dlGds7O5iZnm76WDqdDkPBYFPH+xyv1wuLwpK4kWgUlUpF8bEXl5cxOjr61fuBSqVy9F6m0mlks1lUKpWPjq3T6eByueAfHMTE+LiqRaKiKCI0MtK1WZi9YnFpCdca6FFcLJWQTCaPvqu5XA7VavXoXk2WZZjNZrhdLgSDQYyGQqquWXabDT6vF3v7+4r30WqHiwcOn0O1NDs725PPp06nU3WP5P1kEouLi4gnEicG7gVBgM/nw5mZGQz6fIqOIYoi5ufm8PjJE1VjJSI6bRhgJSKitonH49gOh7G3t4dCofDRClyr1YpgIICJ8XFNVncGA4GeCbAajUbFPZMqlQru3b+PVDr9p3+r1+uo1+sol8tIp9PYjUQAHDw8Bfx+jAwPIxAInPjwu7G52ZXlz9rtj+fPofvM5MDFhQX4vN6m9ylJEn765RfFY6pWqw3/rMvlwrCKbKxkMokHjx6hXC5/8eeKxSIWl5awtr6Oa1evKur1KggC5mZn8ejxY6XD1VS5XD7K0s1kMqjX60f/ZrVaMTw0hMnJyZb3O9vb20N4dxfRaBSFYvHovKnT6eD1eBAaGUEoFFJdhtTr8RxNBtIBt9uteNvNrS388fz5ia/nYRZaoVj8aJLUbrNheHgYIyMjJ/Yyr9frXdv7r9UymQy2trcR/9B/9vj30WAwwOf1IhQKqTrfHfL5fBBFUfE1UKfTaVJmT5IkxONx7EYiSKZSKJfLqFQq0Ol0MJlMsJjNCAaDCAaDqnvPB/x+BAMBRKLRr/5sOp3G//z004n/5nA4cENhT+mV1VVsbG4q2lZNoKydlpaWcPWEoE2lUkHsw3sdjUY/+nyfRJZlZDIZZDIZrK2vY2J8HBfOn1ccuPF6PDAajU29jptbW4oCrAAwPDysSYBVVXlghZ+1Q4VCAds7OyeWbC0UCohEo9jd3cXe/v5Xr6v1eh37+/vY39/H4tISLl64gPHxccVjGx4aYoBVpe3tbcyePXtidn8qlTp4fyORz/ZrPbwnEwThqG9xNBbD4uIirl+7Bo/Ho3hsQ0NDXRVgPVzoG43FkIjHP1oMotfrMeB2Y2x0FENDQ6oXRNlttoavVd1kfnZW8eJMSZLw4uXLr14fZVlGPB5HPB7H8PAwrly6pCjAPTI8jPeLi1254JWIqFsxwEpERC2XTqfx/MWLL/bzLBQKWF1bw9r6Os6eOYO52VlVx/T0ULBAzcTo8srKicHVL5EkCbuRCHYjkaNMgvHx8aNgoSzLzGT74HMZmwBQayLQ+al2PbSq6UccTyTw4OHDr070HletVvHg4UNcvXwZIQV9/YKBAMxms+LSg1pZWV3F23fvPvu7FwoFLK+sYG19HZcvXWpJybJisYiXr14dLYz4VL1eRyweRywex8bWFr65fl1VprJer4fD4fjsZOFppLTMYrVaxYuXL5u+/uTyeSwuLWFxaQlOpxOjoRBGQ6GjbKZwONwzgSStlMtlPH/5Eru7u5/9mWq1enRN83m9uHb1Ksxms+Jj6nQ6eDweJBIJRdtPTU6qblMQTyTwx/PnKBQKf/q3wwB9Pp9HYm8PL1+9wuTEBM7Nz6vKbD83P4/dSOSrizXq9fpnr2FqsvsrlUrfT+hu7+xgdnYWNqsVsiwjFo9jfX0d0VhM1f3q+sYGqrUarl+9qmh7URThGRhoKmiRzWaRTKUwoGAhin9wEAaDoakFYydRWh64WCxqUmp9aWkJoZERiKKIWq2GcDiM9Y2NLz7vfI0kSfjjxQvIsoyJiQlF+3A6nZq8vqfd0vLyUd/PUql00B5jY+OLzwZfUyyV8Pu9e/j+9m3Fi7i8KoKzWkskEnjx6tVnz921Wg3xRALxRAKO5WVcv3btxAVkzRgfH++pAKvL6URQRSnzh48eNX2+CofDKBQKuP3dd4qCrJMTE3jx8mXT2xERnVYMsBIRUUtFolE8evy44UwQWZbxfnERkiTh3Py84uPqdDo4nU6kmww+doJBRVBE7WRkvV7H9s4Otnd2YLfZMDExAaPReOKkLvWWw6xwJcrlMh4/edJUcPWQLMv448ULOF2upidRRFHEaCiEpeXlpo+rlecvXjS8wKBer+Pps2cwGo2a9urMFwr49bffvpo5fGhvbw8PHz3Cre++UxXgYID1Y0aFwapCoaDou3NcJpPB6zdv8ObtW4wMD2N8fLxnqjJoJZPN4t69eyg1+D0AgMTeHu4/fIjb332nKtjodrkUB1gnFQZFDi0uLeHtu3cN/7wgCFjf2EAsFsOd27cVl0x1OBzw+/2Ix+OKtqevk2UZb9+9g9PhUB2o+dTOzg6Gh4YUZ3G73e6mgxabm5uKAqyiKGJoaEhVFqnP61W8kEKL7FngYFHM8soKyuUytra3NQ1ovnj1CoFAQNH3WRAEuN1ufpdV2trawqDXe9CGJRrVbNGuJEl49vw5/vaXvyja3ul0QqfTqb7PUCsSjeLho0cNvy7ZbBa//Por7ty6papCiFYLNNplampK8baLS0uKF4OkUim8ePUKVy9fbnrb0VAIr16/ZjUrIqIGda6BFBER9b1UKoWHjx4pujlfXFrCfjKp6vhqV8i2i5rCno307GtULp/Hq9ev8fTZM832SZ0zNjqquGzsqzdvVGXK1et1PH/xQtG2SjNStLC6ttZ09rYsy3j+/LlmkxCHZb8bDa4e2tvfV1xe89BJpfBOM6XfH4vForpk86HDXoe/373bdLWCXlYul3Hv/v2mgquH0um06vKYX+uT+TkBv19xgBM4KEv55u1bRdsWikU8ePQItVpN8fHV9oijr9vZ2cHbd+80Da4eWl1dVbytXcFnficcVhzkGVFZzltVeWANS62/ffcOq2trmgd71FaTUVs2nA7egyfPnmE3EtG8IlImk0Fc4SIeURQVV9jQyuEzfrOvS71ex4OHD1FUUalGFEXFC0jbTafTKV70ks3l8H5xUdXxt7a2FC200Ov18Cns40pEdBoxwEpERC0hSRKePHum+IFUEAS8fvNG1RjUTHK2U11FYGZyclJ1PxvqT0rL1hYKBezs7Kg+/v7+vqJFEm63W3V5TSVKpZKqwMa2Rhkxb96+RT6fV7Tt4uKiqknATrzu3Uxp4MBoNGJ8bEzj0Zwur16/VlUqfHVtrelFCseZFd4/jCoojX6oWCzijxcvVAXn1QaXA34/zDwP9Kz9ZFJxgF1JP/FqtfrF8t1f4vP5FJe1FwQBQwqDFnt7e4qvse0WU5GB2ukAHH2dmgzjTj/jvnz9WvH9ZqlcVv2MH/D7VW3fLkNDQ4pK9ALAysqKJmNYVrjwpleC2ERE3YABViIiaont7W3kcjlV+9jf30deRanaXgkWqMkUtFmtuHnjhqpSiNR/7Dab4uzmza0tzVbqbynIEhEEAW6XS5PjN2NldVVVubWwwknm4/KFgqos1FK5jP39fcXb98o5s13KKs7NF86fx7CKDKvTLJPJqC7hKUmS4sAPAMVBRr+KSd+l5WVNSj6qCS4LggA/J1V7lizLyChsHaH0PlJpNqgoioorVvh8PsXXq02NFkO1g5qS/UpL3FP7qGlj08nnvv1kUtW9JnAwT6Dm9/d4vaqO3y5KA8GHLXy0EIvFFC1YU1L+nYjotGKAlYiIWmJ1fV2T/UQiEcXb6nsks1Ntv9PBwUH87a9/xcjwsOYlrKg3qZnkV1qy7CSJvT1F26npzaSEJEmqAzrxREJ1meANFeUADynt1QRAVf/WfqTm3KzT6XDj2jVcvXJFcZ/A02ptfV2TEsvN9pM8TkllCM/AgOJJ71qtplnZ0nq9rmqhhpb9pKn9lJaqVVoNJZ5IKD5XKi3zq7TkZq1W06RCR7tIkqR40QWr23Q/NWWlO/n+alGxRRAErKjoK28xm2HpgXurQYVldvf39zXtsbunICDudDo1a3dBRNTvOItCRESayxcKqlalHpdWsXpb7JHJhVqtpipTFzh40Lx+7Rp+/BBopdPNq3Bld71eR1Jl7+Pjstmsogkkp9Op2RgasZ9MqionChxMhKr9HmuRBZtVmL0EADoGWD+iJnvo0GgohL//+CMuLiwoKsF52siyjF0VC6uOU3P/oCjA6vEoPl4sHtd0MlXNazjo83FStYcp/RypWWCjdHGAkkxUQRAUB1jDu7uafs/aQWnJZ4HX865XU/FZFDt4jlZTuvq4aDSqamFwu58VmuVwOBRn2itdoPo5Sp7tRFFU1JubiOg04l0XERFpLqYig+pTWTUB1h6aXEholDXodDpx/do1/P3f/g1Tk5OK+75Qb3M6HIq2KxSLmmZBC4KgKHDZ7t5SexpNZKgpi14sFjXpC5dTsQ8GVT6m1QSXTqfD5MQE/u3HH3Ht6tW2Z2j3kmw2q3qxw6FSqaQ4Q0jJd8GlorS5ml58J0mlUopfR6PRyElVasrW9raiewclwdJBFb1b1WR29xpez/tbp97fSqWiWQ/jSqWiKLPyULdfp9QEgLXuE11SeD/AhYFERI3hrCsREWlObV+W47SaaO12O+EwxsfGNNufzWrFwoULmJ+bw9b2NtbW11VltlHv0Ol0ivuvFgsFzcuOVRQEONpd9iuVSmmyHzXnKzXZdsep6elMHysWi9jf31eVmXicKIoIjYwgNDKCZCqFtbU17ITDqktL9xM1k60nqVSrbetVp2YyNanROei4/WRScY9Lh93Oe4YuIAgCjEYjDHo9dHo99Ho9dDodREE4+K8o/um/DoULrNQoFApI7O0pKoc5PDyMtSbaioyMjDR9DOBg8ZGWzydKiKIIo9EI/Yf3Uq/XH7x3onjie6nT6Vjqt4fo9XoYDIaD/+r1EHW6j97bT9/fXihx+ymlPZ4/J5VKwaew6o6jywOsLhX3BKVyWdPvfl1hJny7F7wSEfUqBliJiEhzWgUKAHXlk3pJPB5HJpPRvNyRXq/H5MQEJicmkNjbw9r6OnZ3d9mrtY/ZbDbFK9v9fj/+z3/9l8Yjal67AiKHtCgFCygvzQhAs7LqSssJ0slW1tY0C7AeN+B2Y+DKFVw4fx6bW1tYW19X3Y+7H2j1XTxUU9HjrllKMz1kWW5JMFNNBozD4QA0KFlOjbFarXC73XA6HLDb7bBZrbBYLDAajT2Tibi5taUowOr1eGA2m1Eqlb76s4IgKF40sNnG7FWHw4GBgQE47HbYbTZYbTaYTSbFmbfUPXQ6HVwuF9wuF+x2O+x2OywWC8wm06moGlTU+D5FTeUXc5cH/5QudgWAO7duaTgS5U7DZ5qISAs8WxIRkaZkWVb1sPSp0xQseP3mDb779tuW7d/n9cLn9aJYLGJ9YwNr6+uKyydS9zL34Ir4T7UzY0OSJBSKRU32pSbAWtRoDJIkQZblnpmU73Y7OzuYnpqCZ2CgJfs3Go2YmZ7G9NQUotEolldXNStZ3Yu0vH8A2rdI6zBrSYlSqdSSLGY1r6VdxcQwfZ1Op0MwEIDf74d/cLAvrtu7u7uoXrjQ9AKpwzLBq2trX/3ZgN+vaAGWLMvYUtgnthFmkwnBYBABvx8+n49BiT7jcDgwFAwiEAjA7XL1VAsarSktNfs5aq5Tpi5fsNCLGcqfYgY9EVFjeOdHRESaqlQqzI5UKBaPY219HZMTEy09jsViwfzcHGamp7G2vo7llRUGWvtIPzzQAwcP9WoClo3Ssgy5mnNfI9k7zYyDAVZtCIKAJ0+f4q8//NDSzGpBEBAMBhEMBrG3v4/FpSVN+5n3iqKG3wMAQJvuR9QEyFrVCkHNog2TyaThSOiQw+HAzNQUhoeH+y4IV6/XsRMOY2J8vOltR0ZGGgqwNtuv9VAsFtM8MAQcBHwnJybg9/t5ze0zoihibHQUE+Pjqvpr9xut21CouU4Zu/w61e0Zto1ggJWIqDH9dVdPREQdp1UW1mn18tUrWCwWBAOBlh/LYDDg7JkzmJyYwOLSElZWVxkc7wPtLq/b67qlz/NpytbvNYVCAQ8fPcK3N2+2ZbLJ6/Hgu5s3EY/H8erNG83L5nazbvk+NsugIljWqr7JarJ3dX0W/Os0q8WC8+fPKw4Q9orNzU1FAVbPwAAsFssXnyEOF6EoGpfG2aterxcL588z8NanxsfGMDc72xeZ5VrTutqCmuuUvsuDf0Y+jxERnRqnt7YFERG1RJVBAlVkWcajx4+xEw637ZgGgwHnz53DX3/4AS6Ne8BS+3G1cXO6JXv7tPSb7lWJvT3cf/iwZcGwkwwODuIv33+P+bm5U5EdJcty13wfmyWqOO+26ruvpgJAt09c95KpyUn8+Le/9X1wFQCSqZTifsJfe32UlgeuVCrYjUQUjelToiji0sWLuHPrFoOrfchiNuP7O3dw+dIlBlc/Q+sAq5rrVDeXapZluavHR0RE2uIZn4iINNWOkp79TpIkPHr8GG/evm1JX7bPcTqd+OH77zE+Nta2Y5L2GGBtTrcENtv5XSdlEokEfvntN6RSqbYdUxRFnD1zBndu34axy/uNqVWr1Xo2kKxTMZEqt+i7ryYrvt/K13bKlcuXsXDhwqm6LivNFh0ZGVH175+zvbOjSXUWo9GI72/fVpShS91vwO3GX374oWX91ulktVpN8fezmwOYOp2uZ+9niIioed17RSIiop7EIIE2BEHA0vIyfv71V+zt77ftuKIo4vKlSzgzM9O2Y5K2+EDfHJbFpmbk83n88ttvePP2bVvLOnsGBvDD99/D3OU9x9To5fsHVWeRFp2zVe2V1xHVrl6+jLHR0U4Po+22trcVfZcH3G5YrdYT/00URcWtM7QoD6zX63H7u+/gdrtV74u6j8vlwrc3b7L3dAeIotiXzy3dHPwlIiLt8axPRESa6uUJ0m6UyWTw2++/49GTJ8jlcm077rn5eWay9ih+B5vD14uaJcsylpaX8d//8z/Y2Nho22fIZrXi1q1bfZtd2MuLHVRli7You1FNH1VWI1FncmICo6cwuAoc9FGOxmKKth0ZHj7x74OBgKLzXjqdRjqdVjSW465cvgwnW2j0Jb1ejxvXrvV9hQitaB04VHM/083377yGEhGdLv35dE5ERNRnwuEwwuEwRkMhnD1zBna7veXHXLhwAclUCplMpuXHIu3woZ6oPUrlMv548QKLS0s4e+YMRkdHW5614LDbceniRTx5+rSlx6HmqDnvqgmEfnG/KgK3Eq8jiplNJpybn9dsf7IsI5vLIZvJIJPNolQuo1qpoFKpoF6voy5JkOr1oz9fuXwZQ8GgZsdXYmtrS9EYRoaHsbS8/Ke/H/5M4PVrtMheHR4a0rR/br1eRyabRSaTQTabRaVSQbVaRaVaRb1WO3o/JUlCrV7H33/8kZmVLTQ/NwebzabZ/qrV6kFgP5NBoVBA+cP7W61UIMky6rXa0XtrtVrxl++/1+zY7aD1Ai9V16kuDrDKsgxZlvsyO5eIiP6MAVYiIqIesrW9jc0PE1dTk5MYHBxs2bF0Oh0uXriA3+7ebdkxSHtqJvozmQzK5bKGo1Gul7PZ6HQpFIv448ULvHv/HhMTE5gYH2/phHhoZAQbm5tIJBItOwY1R00Gq6FFAVY1E+HtLH/db2ZnZzUJQqRSKWxsbiISiaDUxHW5G66dkWgUpVIJZrO5qe1cLhdsNhvy+fzR3+l0OgT8/qbHIEkStra3m97uOFmWMTc3p2ofhyLRKLa2txGNRrkQrktYrVZNeurW63Vsbm0hvLvb1HW5FwPnWgdYVV2nuvx7VK/XFf1+tVoNyWSyBSNq3vFzMRERfR4DrERERD1GEAREolFEolE4HA5MT04iFAqpWgX8OV6vF4ODg4jH45rvm1qjVCop3nZlbQ2bm5sajobo9CiVy3j3/j0Wl5YQCoUwPTnZsrKS87Oz+JUB1q6h5rz7ub6TalmaDG4dVywWNRzJ6aHX6xEaGVG1j0qlghevXmF7e7tns59kWcb2zg5mpqeb3jYYCGBldfXo/31er6IgxW4kgmq12vR2x/n9fjhUVoxJp9N4/uIFkqmUqv2Q9sY0qDqxEw7j1evXqq4BvUTrPvB2FdnDlS5ZEPo5xVJJ0fmjWq3i7v37LRgRERG1CnuwEhER9bBsNos/XrzA//3HP/Du/fuWZB+yF2tvUTPJo2ZCnogOSJKEzc1N/PPnn3H33j1Eo1HNj+HxeOBwODTfLylTr9cVByUNBkNLMpnUlL1sJmOS/mUoGFSVkVUoFPDLb79hZ2enZ4Orh5SW5x30+T7+f4WVWrRYLPa5nrCNisXj+PX33xlc7VKhUEjV9otLS3j85MmpCa4CgNli0XR/aq5T5UpFw5FoT+nnwmw29/z5n4jotGGAlYiIqA9UKhW8X1zE//3HP/Di5UsUNXzY9w8O8kGvhxQKBcXbWjWeOCE67eKJBO4/fIiffvkF4d1dTct3KimbSa2Ty+UUb6tlD8BDagLwLAuozKfBwWbIsoynz571zWufzWYVBRa9Xu9H95xKznPFYhExDSqvqHk/S6USHj95orocMO+/W8NqscCmonpALBbD23fvNBxRb1Cb0f0pu4r9lbq80oLS5zFBEJour05ERJ3FACsREVEfkSQJa+vr+Md//zdevnqFN+Q5FAAAIABJREFUigarew0GQ8vKXJL2iqWS4vfd4/VqPBoiAg7KRD56/Bg//fILorGYJvv0ejya7Ie0kVMRGPMMDGg4koNgndvlUrx9Kp3WcDSnh0vFax7e3cXe/r7qMZiMRtX70IqSLFK9Xg+32w3goEelkgCM0uzZ4wwGg6ry3e8XF1WXKD4cB2lPzXcVAF6+fq16DL3Yg9VsNms6bjWLGNRcc9shk8ko3pb3d0REvYUBViIioj4kSRJW19bwj//5H03KpKlZYUztl1Y4OW632VrWD5CIDibc7j94gPsPHqiuNMDzcnfZVxEcCwQCGo4EcLtcijNgZFlGNpvVdDyngSzLqq6fOzs7mozD2EVBm51wWFEG5+GCA6ULD7a3txVtd5ya3pCSJGE3ElE9BpPJxAzWFlFTNSCTyaiqWHComxZDNMOjUfDPbrereh+0eA9aSc1CJb/C0uhERNQZDLASERH1sWq1imfPn+PJs2eQJEnxfsxdNGFHX7efTCreVm3PMSL6umgshp9+/lnVd5Ul5LpLPJFQXALaMzCgaaZaMBhUvG0qnVZd1vQ00uv1qvqvJlWcCw4ZDAZVgUGtVatV7O7uNr3dwGGAVUEgJ7G3p0lmm1FF8KtQLKKsQR/jgQ+ZvKQ9Ne+vmuv2cQMaVy5olyGNFgQNqbhOAUCmyxcCpdNpxc/egUAAOp1O4xEREVGrMMBKRER0Cmxvb2NpeVnx9momDfuV0k6Kotj62y81JUinp6b4UE/UBpVKBQ8ePlRcRpLn5e5SLpcVVw8QRRFTk5OajEMQBIyPjyvePhqNajKOZvV6pp6a66Ysyyhr0NJh0OfrutdRSbnew7YUTgV9hLUoDwwAOhXn17LK6gSH/Oyz3TJqrp9aBM8BYLBHsxSHhoZU33/odDpV17xSqaS4x2m71Ot1JBIJRdsajUZMTkxoPCIiImoVBliJiIhOifX19U4Poa+oyQhudd+lZDKJksIJPpPJhOmpKY1HREQnqVQq2AmHOz0M0ojaxS1aBM3Hx8ZgUZHdrOZ3UJP5etorZSjNfj5uqguv3fFEoulAiM1qhSAIcHwItDaqVqsh3AXnU/Xv5EE2cmhkRIM9kda0+K4ODg4qWkDQDfR6vernhMmJCVVVOLToV90OERULlmamp9mDmYioRzDASkRE1GF6vb4tGYOlclnxpADLBf5ZrVZTvK3SvmLNCCsoy3do9uxZeDXqsdQoZs1St2lXwEfpYgg15yBqjY3NTcXXWYPBgPPnzqk6vtFoxOzZs4q3z+VySKVSirevq7kutvmaozU1i64EQVBd8jsYCLT9ut2oZrNKRVGEy+VqeqGA0p6vJ1HzWdbi2jF79iyDKy2k5nOiZgHLofm5OdX76KSZ6emjTPNmWS0WnD1zRtXxY/G4qu3bJby7q/jaYDKZcO3KFY1H9HV8HiMiah4DrERERB1mt9vxv/7933H+3DnYWtg7y2QyKS4dV9KoHFY/UVMiTKtSkF+ytrameFtRFHH92jXY7XYNR3Qyi9mMc/Pz+I+//73rShvS6Xb58mV8f/s2RoaHW/rZVJrRrlWZQtJOsVhUlbEyMT6uODNIr9fj5jffqArUrW9sKN4WgKoyt06nEz6vV9XxO6laraoK2qj53W02G65cvqx4+1bb2tpqeuGBkv6jWxqVBwaAisLS7cDBfb2a7+FQMNiW+8TTTGlpfgDw+nyqjr1w4ULP99fV6/X47uZNWK3WprYzGo24efOmqsUDsix3rJR9s8rlsqoFr4FAABfOn9cka/prhoJB3L51C2dmZlp+LCKifsMAKxERURcwGAyYmZ7G33/8EXdu38bE+LjmZWTVlBrL53IajqQ/FItFxdv6fD5FWUZmkwnuBidlcvm8qlKPZrMZP9y5g2AgoHgfn6PT6TA8PIxvv/kG//73v+PMzAyMRqPmxyFSRZbh8Xhw/do1/Od//AcuLizAq3EASKfTYSgYVLRtLp/XdCykDTWLWwDgwvnzuHzpUlMT0G6XCz98/72q6gjValV1/0pJklQF/q9cuQKLxdLUNoIgwOvxdLwnsSAIKKrovak0sO5wOPDdzZtdfQ0tFItI7O01tU2z59pcLqdp2dCiyv6OM9PTirYbCgZx9coVLjhrMTX9O+02m+Lr9tzsbN8Ez81mM/7y/fcYHR1t6OddLhfu3L6tujRyIpHoqQVmq6urqrafnprCzW++aUlmqcPhwPzcHP7j73/HNzdu9PQiJyKiTursUwgRERH9idfjgdfjwcWFBewnk4jFYojF46rK9vn9fsXlqCRJQiabVXzsfqU2uDE3O4sBtxuLy8vYP2FSUBAEWK1WuF0uDAwMwOf1wuVyYWt7G0+fPWvoGG/fvYN/cFDxRJ3BYMA3N24gvLuLxaUlZDIZRfsBAKvVikGfD36/H/7BwY5PhhM1w2g0YnJiApMTEyiXy4jGYojFYkjs7Sme6NPpdLh29ariTCc11wRqnXgigXg8jsHBQcX7GB8bw/DQEDa3trC7u4tUOv2n7EiTyQSv14vQyAiCgYDqgMzK6qqqrK5DuVxO8QIxq8WCv/7wA5aWl7G5tYXKCRmxBoMBTocDAwMDR9dGo9GIf/z3f3e8bHY2m4VdYSUSt9uNyxcv4vnLlw1lKwmCgLHRUVw4f74nrqdbW1sYbCLzb2R4uLn9b283O6QvKpXLqFarijPtpiYnkclmsbm52dDPGwwGzJ49q7q3JTVG7XPN5UuXUCgUkG7wvthms+HiwgL8Kq4L3choNOLq5cuYmZpCeHcXkWgUxWLx6Nyt0+kwMDCA0VAIoZERiKL6HB+1lRbaLZlKYTcSURyUBw4WXvzb3/6GpeVlbGxuKi47LIoiPB4PBn0+DAWDcPRoH2Aiom7T/XfiREREp9RhVobX48H83BxqtRr2k0kkk0mkMxlks1kUCoXPPmQZjUZ4PR6MjY0h4Pcrnnzd399nD9YTpNNpyLKsalI7EAggEAigWq0in8+jVq9Dr9PBYDTCYjarnohIp9PY3t5ueHX5SQRBwMjwMEaGh7G/v494IoFEIoFCoYBKtfrRhLZer4fRaITJZILNZoPNaoXL5YLb7dakZxVRNzCZTBgbHcXYh+/VYeZUKpVCNptFLp//YtDV6XQiGAhgYny86Wy94+KJhOJtqbVevHqFv/3lL6rO4QaDAdNTU5iemoIsy6hUKqhWqxAEAUajUdP+jOVyGSsqs2wOpdJpVZneRqMR58+dw7n5eeQLBVTKZUAQoNfpYLFYurovZSqVUjWJPj4+DpfLheWVFcTi8RMD3m63G/7BQYyPjTVdnrOTwru7WLhwoSXvnyRJqrOvT5JMJuH3+xVtKwgCrly6hGAggNXVVezt7/8pcK7T6eDxeBDw+zE+NtYTgfJ+kc1mUavVFL/mRqMRP3z/PdbW17G5tXXiAkSTyQSvx4Ph4WEMDw31dVay0+mE0+nE3OwsgIPvpCRJmn+mC8UidiMRTffZDq/fvEHA71d1T2CxWHBxYQFnz5w5eBbb20MymUSlUkGlUjk6vxzeIxiNRlgtFthsNtjtdrhdLjidTvZYJSJqAd7BERER9Qi9Xg//4OCfVj+XSqWPen+JOh3MJpNm5eK2d3Y02U+/qVarSKfTDZfs/RKDwaDJfk7y8vVr+Hw+VYGcQx6PBx6P56PyxocBfi1WpRP1IrvdDrvdjvGxsaO/q9frKJXLqNdqqNfrEEURer0eFotFk+9KsVjEXpMlN6l9crkcVtfWFJcJ/ZQgCDCZTJq3Djj04uVLzbI/E4mEJll4giAcZIO2sDe91qKxmOJqIYfcbjeuX7sGWZZRLBZRrVYhyzKMJhNMRmPPTo7X63WEw2GMj49rvu94PI6SivLMnxONxRQHWA8NBYMYCgYhSRIKhQJqtRpEUTwKgPDeqTNkWUY8kVC1IEIUxaNFMLVaDcViEbV6HQa9HgaDoWXn614gimJLPtvvFxfb0o9Ua/l8Hu/ev8e5+XnV+zKbzRgNhTAaCn3095Ik8XxCRNQhDLASERH1OLPZrLjE5NdUKhUGWL8gEo22LDCqlWq1iqd//IFb337bktXzfJgn+jOdTgdbC7PLeq1E3mn09t07eD0eDKjoi9oO2zs7CO/uara/eCKhKjOsl6XTaWRzOTjsdtX7OmwT0E82NjdbEmDdaEH2KnCQdXv+3DlN7nNEUYRdg88FaWdnZ0dVgPU4vV7PcqstlslkGi653Y2WlpcxODjYVKn0ZvB5jIioc3gGJiIios9aXFpieeAv2N7Z6YmV1IlEAq9ev+70MIhIA6VSSbNyrtQ6kiTh4aNHinv0tkMqlcIfz59rus96vY5dDQO2vWZ9fb3TQ+ja/szJD2XUtVSpVBBpUcnQUqmEaCzWkn03SpZlpNPpjo6hX4V3d1uS+dyMSqWCfKHQ0TH0AkmS8Ezja1UnPH7yBLlcrtPDICIijTHASkRERCdKJpNYXVvr9DC6Wj6f75leQKtra3i/uNjpYRCRSn88f86FLz2iVC7jwaNHJ/bS7LR8oYAHjx615LO0fIoXAKxvbKBYLHbs+JFIBL/89hty+XzHxvAlWvdK3drebulCt7fv3nV0Id2bt2/x8NGjnljM12tkWcbi0lLHji9JEh48eoT37993bAy9YnllpWsXjjSjUqng7v37KHY4sE9ERNpigJWIiIj+pFgs4vGTJ5zQacDbd++O+pB2u3fv3+PV69d8X4l61OLSUsczqqg5yWQSv9+92/FMqeNyuRx+//33lo0pk8lga3u7JfvudpIk4cXLlx05diqVwuOnTyHLcteW0tza3tb0nknrgO2nstlsxxYbrq+vY3llBYViEfFEoiNj6HfrGxtIJpNtP64sy3j67Bn29/cR3t1FpVJp+xia9fvdu7h3/37bn3ki0SjevnvX1mO2UrFYxK+//opMJtPpoRARkUYYYCUiIqKPlEol3HvwAIUOZmD0klwu11OZoSurq3j0+HFPTOYQ0b+srq311STjaZLOZPDb3btdkVWY2NvDb3fvtjyD5vWbNx3N5OykSDTa9jLe+8kkfr937ygjeWtrqysXf5XLZc0WiaRSqbYEKd68fYv9Ngfh1tfX8fxYoH6jSwPmvU6WZTx5+rStpdwlScKzP/7ATjgM4KCs+uGfu1UqlUJibw+xeBxPnz1r20LNvf19PH7ypC3HaqdiqYTf7t5tWXlzIiJqLwZYiYiI6EgylcLPv/6qeY+sfvd+cbHrJ0eO241E8NPPPyMej3d6KET0FZIk4eWrV3j56lWnh0Iq5PN5/PTzz1hbX+9IFQFZlrG0vIy79+61JZhQLpfx8PFj1Gq1lh+rG716/RrbOzttOVYsHsfde/c+eq1L5TJiXZrtvqVR1mmrs1cPSZKEBw8fti3jbHFp6aPgKgDs9kiWYy/KFwq4//BhW17fWq2Gx0+e/CnDv9sD6GsbG0d/3gmH8ejx45a3KojGYrh3/37ftkSoVqt48OgRnr94cWqvk0RE/YIBViIiog6TJKnjJVtrtRrevnuHX3/7ravKGPYKQRDw5OnTri3Jd5JiqYTf793Do8ePO55VlUyl2roinqgRtS6Y1Nvb38dPv/zCfth9ol6v48XLl7h7/35bywPu7e/j519/xZu3b9t6nk2lUrh7/35bs8O6yZOnT7G8stKy11yWZbx7//6zQYh2BSCbFYlGVd9rSpLUtgA2cNA78dfff0eshQvTKpUKHj56dGKlAlmWT23Z7XZIpVL47e5d5AuFlh0jk83il99+w+4JWYvpdBrpdLplx1ajWq1i55Pv2m4k0rKqDLIs4/3iIu4/eNC3wdXj1jc28N///CfWNzY6WnWgVqthbX29a68bRETdTN/pARAREZ12mUwG//f//T+EQiGERkbgcrnaduxyuYzNrS0sr6xwZbxKsizj2fPniCcSOH/uHMxms+bHKJVKSOztabY/QRAQ3t3FbiSCkeFhTExMwOvxaLb/L6nVagjv7mJ9fR3JVKotxyRqxuMnT7CxsYFQKIThoSHo9e15dJJlGYm9PaysrLDfap9KJBL4n59+wvDQEM6eOQO3292S48TjcaysriISjUIQhJYc42uSyST++fPPuLiwgOGhIc33f/h9qVSrmu9bC6/fvEEsHsfChQtw2O2a7Text4fXb94g9YXr52EgsxX3I2rIsoydcBjTU1OK97EbiaDa5ve8Vqvh7r17mJ6awuzZszAajZrsV5ZlbG9v4827d18MPG9sbqp6zejLstks/vnTTzh/7hzGx8Ygitrko9RqNSwtL2N5ZeWLAbSNzU1cXFjQ5Jha2tzaOjHQmUql8NPPP2P27FlMTU5Cp9OpPtZ+MomXr1598bzWj0qlEp6/eIGVlRVMTExgbHQUBoOhLcfOZDJY39j47PtMRERfxwArERFRFyiVy1heWcHyygrsdjsGfT74fD54BgY0nxgrFouIxeOIRqOIRKPMGtTY9s4OdiMRjI+NYXxsDE6nU9X+CoUCEnt72N3dRTQWa8n7Jcsytnd2sL2zA7vdjuGhIQQCAQy43ZpOymcyGURjMcTicezt7fGzR10vnkggnkjgxcuX8Hm98Pl88Hm9cDqdmk2+AgfZWMlkEtFYDOHdXeS7oFcntZYgCNiNRLAbicDtcmFoaAjDQ0OwqwzCpdNp7EYi2AmHkcvljo7VSeVyGY8eP4bb7cbUxASGVC5YqNfrSKVSiMZi2N7ebnk/WbXi8Tj++dNPGA2FMDkxoTigXqvVEIlEsLG52dBiq8OsxzMzM4qO10pqg4WdyrISBAGra2vY2t7G1OQkxsbGYLVYFO2rVCphe2cHG5ubR9/VL8lms0gmkxgYGFB0PPq6wyoDq2trmJ6cxMjIiOJAVyaTwebWFra2txtaxLq1vY3z585pEqjUiizLWF9f/+y/1+t1vHn7Fqtra5gYH8fY6CgsTX4fJElCNBbD+vp6SzPEe0Eun8er16/x5u1bBPx+DAWD8Pv9MJlMmh2jWq0e9NONxRCNxU5tr3QiIi0JFy9e5MwWERFRF7PZbHA6HHA4HLBaLDCZzTCZTNDr9TDo9RBFEaIoQhAEyLKMer2OuiShWqmgXKmgVCwil88jn88jmUx2/URkv7FaLPANDsLtcsFut8NiNkOv1x9NLtfrddTrddTqdVTKZRQKBeQLBeTzeezv73f0/dLpdHC7XHB9GLvZbIbVYoHBYIAoike/gyzLkCQJdUlCrVpFtVpFqVxGsVhEoVBANpdDOp1ue7YJUavo9Xq4nE44HA7YbDaYzWaYzWYYDYaj77cgCEeBrcNS8JVqFdVKBaXD73o+j3Qmg3Q63dHScNQ9bFYrnC4XXE4nnE4nzB+uGYYPnytJko6uG6VyGcUP14xkKoVkMtkT51lRFOH1euEZGIDT6YTFYjn4PXU6CILwr9/xwzWlWCohn8+jUCggk8lgP5ns6QU6VqsV/sFBuFwuOOx2mC2Wo/s5WZZRq9VQr9dRLJVQyOeRzeWQTCaRTKV6+vfuR7IsY8Dths/ng8vlOrgefLhHP/5ZrlarKBSLKBaLSKfT2E8mkclkOr74gb5MEAQMDg7CMzAAl8t18BxmMh0FQWu1GiRJQqVSQb5QQKFQQDqTwV4igdIpLY3ucrkw6PPB5XTC9uHZ4fDcXq/XUalWUcjnkcvnsbe3h8TeXk9ctzpFlmXYbTa43G44HQ7YrFZYjn0OD881hz8rSRKq1SqqtRoq5TKKpRJKpRJy+TwymQxyuRyvI0REGmOAlYiIiIiIiIiIiIiIiIioQdrVtSIiIiIiIiIiIiIiIiIi6nMMsBIRERERERERERERERERNYgBViIiIiIiIiIiIiIiIiKiBjHASkRERERERERERERERETUIAZYiYiIiIiIiIiIiIiIiIgaxAArEREREREREREREREREVGDGGAlIiIiIiIiIiIiIiIiImoQA6xERERERERERERERERERA1igJWIiIiIiIiIiIiIiIiIqEEMsBIRERERERERERERERERNYgBViIiIiIiIiIiIiIiIiKiBjHASkRERERERERERERERETUIAZYiYiIiIiIiIiIiIiIiIgaxAArEREREREREREREREREVGDGGAlIiIiIiIiIiIiIiIiImoQA6xERERERERERERERERERA1igJWIiIiIiIiIiIiIiIiIqEEMsBIRERERERERERERERERNYgBViIiIiIiIiIiIiIiIiKiBjHASkRERERERERERERERETUIAZYiYiIiIiIiIiIiIiIiIgaxAArEREREREREREREREREVGDGGAlIiIiIiIiIiIiIiIiImoQA6xERERERERERERERERERA1igJWIiIiIiIiIiIiIiIiIqEEMsBIRERERERERERERERERNYgBViIiIiIiIiIiIiIiIiKiBjHASkRERERERERERERERETUIAZYiYiIiIiIiIiIiIiIiIgaxAArEREREREREREREREREVGDGGAlIiIiIiIiIiIiIiIiImoQA6xERERERERERERERERERA1igJWIiIiIiIiIiIiIiIiIqEEMsBIRERERERERERERERERNYgBViIiIiIiIiIiIiIiIiKiBjHASkRERERERERERERERETUIAZYiYiIiIiIiP7/9uxAAAAAAECQv/UKA5RGAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEni2iZAAAKH0lEQVQKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGASrAAAAAAAAACTYAUAAAAAAACYBCsAAAAAAADAJFgBAAAAAAAAJsEKAAAAAAAAMAlWAAAAAAAAgEmwAgAAAAAAAEyCFQAAAAAAAGAKJKYjO2gCKXUAAAP0aVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8P3hwYWNrZXQgYmVnaW49J++7vycgaWQ9J1c1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCc/Pgo8eDp4bXBtZXRhIHhtbG5zOng9J2Fkb2JlOm5zOm1ldGEvJz4KPHJkZjpSREYgeG1sbnM6cmRmPSdodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjJz4KCiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0nJwogIHhtbG5zOkF0dHJpYj0naHR0cDovL25zLmF0dHJpYnV0aW9uLmNvbS9hZHMvMS4wLyc+CiAgPEF0dHJpYjpBZHM+CiAgIDxyZGY6U2VxPgogICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSdSZXNvdXJjZSc+CiAgICAgPEF0dHJpYjpDcmVhdGVkPjIwMjEtMDUtMDQ8L0F0dHJpYjpDcmVhdGVkPgogICAgIDxBdHRyaWI6RXh0SWQ+YjJiN2YwNzctMDFmNy00MWRmLThmOTEtODdmMjI2MDE3NGQ2PC9BdHRyaWI6RXh0SWQ+CiAgICAgPEF0dHJpYjpGYklkPjUyNTI2NTkxNDE3OTU4MDwvQXR0cmliOkZiSWQ+CiAgICAgPEF0dHJpYjpUb3VjaFR5cGU+MjwvQXR0cmliOlRvdWNoVHlwZT4KICAgIDwvcmRmOmxpPgogICA8L3JkZjpTZXE+CiAgPC9BdHRyaWI6QWRzPgogPC9yZGY6RGVzY3JpcHRpb24+CgogPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9JycKICB4bWxuczpkYz0naHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8nPgogIDxkYzp0aXRsZT4KICAgPHJkZjpBbHQ+CiAgICA8cmRmOmxpIHhtbDpsYW5nPSd4LWRlZmF1bHQnPk9tYnJlIEJsdWUgU2t5IEZhY2Vib29rIFBvc3Q8L3JkZjpsaT4KICAgPC9yZGY6QWx0PgogIDwvZGM6dGl0bGU+CiA8L3JkZjpEZXNjcmlwdGlvbj4KCiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0nJwogIHhtbG5zOnhtcD0naHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyc+CiAgPHhtcDpDcmVhdG9yVG9vbD5DYW52YTwveG1wOkNyZWF0b3JUb29sPgogPC9yZGY6RGVzY3JpcHRpb24+CjwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cjw/eHBhY2tldCBlbmQ9J3InPz47zIHyAAAAAElFTkSuQmCC".getBytes());
			 item.setPhoto(decodedByte);
			 
			 
			 item.setType("This items is not available");
			 
			 
			 itemRepository.save(item);
			 removed=true;
		 }
		 return removed;
	 }
	 
	 public List<ItemDto> getItemsByUsername(int distanceValue, String username){
		 com.curio.curioapp.curioappbackend.model.User user=getCurrentlyLoggedInUser();
		 List<ItemDto> sendingItemList = new ArrayList<>();
		 if(user!=null) {
			 List<ItemDto> itemList=showAllItems(distanceValue);
			 for(ItemDto i:itemList) {
				 int editDist = calcEditDist(i.getPostedUser(), username, i.getPostedUser().length(), username.length());
				 if((editDist < 3 || i.getPostedUser().contains(username)) && !(i.getType().equalsIgnoreCase("This items is not available")) ){
					 sendingItemList.add(i);
				 }
			 }
		 }
		 return sendingItemList;
	 }
	 
	 public List<ItemDto> getItemsByType(int distanceValue, String type){
		 com.curio.curioapp.curioappbackend.model.User user=getCurrentlyLoggedInUser();
		 List<ItemDto> sendingItemList = new ArrayList<>();
		 if(user!=null) {
			 List<ItemDto> itemList=showAllItems(distanceValue);
			 for(ItemDto i:itemList) {
				 int editDist = calcEditDist(i.getType(), type, i.getType().length(), type.length());
				 if(editDist<2  && !(i.getType().equalsIgnoreCase("This items is not available"))) {
					 sendingItemList.add(i);
				 }
			 }
		 }
		 return sendingItemList;
	 }
	 
	 public List<ItemDto> getItemsByItemName(int distanceValue, String itemName){
		
		 com.curio.curioapp.curioappbackend.model.User user=getCurrentlyLoggedInUser();
		 List<ItemDto> sendingItemList = new ArrayList<>();
		 if(user!=null) {
			 List<ItemDto> itemList=showAllItems(distanceValue);
			 for(ItemDto i:itemList) {
				 int editDist = calcEditDist(i.getItemName(), itemName, i.getItemName().length(), itemName.length());
				 if((editDist<3 || i.getItemName().contains(itemName)) && !(i.getType().equalsIgnoreCase("This items is not available"))) {
					 sendingItemList.add(i);
				 }
			 }
		 }
		 return sendingItemList;
	 }
	 
	 
	 public boolean setSoldFlag(long itemId, String flag) {
		 boolean set=false;
		 com.curio.curioapp.curioappbackend.model.User user=getCurrentlyLoggedInUser();
		 if(user!=null) {
			 Optional<Item> itemFound = itemRepository.findById(itemId);
			 if(itemFound.isPresent()) {
				 Item item=itemFound.get();
				 item.setSoldFlag(flag);
				 itemRepository.save(item);
				 set=true;
			 }
		 }
		 
		 return set;
		 
	 }
	 
	 public boolean updateCurrentGeolocation(CoordinatesDto coordinatesDto) {
		 com.curio.curioapp.curioappbackend.model.User user=getCurrentlyLoggedInUser();
		 boolean updated=false;
		 if(user!=null) {
			 user.setLongitude(coordinatesDto.getLongitude());
			 user.setLatitude(coordinatesDto.getLatitude());
			 userRepository.save(user);
			 updated=true;			 
		 }
		 return updated;
	 }
	 
	 public StatsDto getMyStats() {
		 StatsDto statsDto=null;
		 com.curio.curioapp.curioappbackend.model.User user=getCurrentlyLoggedInUser();
		 if(user!=null) {
			 statsDto=new StatsDto();
			 statsDto.setItemsPosted(user.getPostedItems().size());
			 statsDto.setInquiriesMade(user.getSentInquiries().size());
			 statsDto.setInquiriesReveived(user.getReceivededInquiries().size());
			 statsDto.setItemsInWishlist(user.getInquiredItems().size());
		 }
		 return statsDto;
	 }
	 
	
	private ItemDto mapFromItemToDto(Item item) {
		ItemDto itemDto = new ItemDto();
		itemDto.setItemId(item.getItemId());
		itemDto.setItemName(item.getItemName());
		itemDto.setType(item.getType());
		itemDto.setDescription(item.getDescription());
		itemDto.setQuality(item.getQuality());
		itemDto.setPostedTimeStamp(item.getPostedTimeStamp());
		itemDto.setSoldFlag(item.getSoldFlag());
		byte[] decoded = Base64.getDecoder().decode(item.getPhoto());
		itemDto.setPhoto(new String(decoded));
		itemDto.setPostedUser(item.getPostedUser().getUsername());
		
		com.curio.curioapp.curioappbackend.model.User user=getCurrentlyLoggedInUser();
		double longitudeC=user.getLongitude();
		double latitudeC=user.getLatitude();
		double longitudeP=item.getPostedUser().getLongitude();
		double latitudeP=item.getPostedUser().getLatitude();
		
		double d=distance(longitudeC,latitudeC,longitudeP,latitudeP);
		itemDto.setAway(d);
		
		int inquiries= item.getInquiries().size();
		int inquiredUsers=item.getInquiredUsers().size();
		
		itemDto.setInquiries(inquiries);
		itemDto.setInquiredUsers(inquiredUsers);
		
		itemDto.setSale(item.getSale());
		itemDto.setDonation(item.getDonation());
		itemDto.setExchange(item.getExchange());
		itemDto.setRenting(item.getRenting());
		itemDto.setLikes(item.getInquiredUsers().size());
		
		return itemDto;
	}
	
	private InquiryResponse mapFromInquiryToDto(Inquiry inquiry) {
		InquiryResponse inquiryResponse = new InquiryResponse();
		inquiryResponse.setFrom(inquiry.getSentBy().getUsername());
		inquiryResponse.setTo(inquiry.getReceivedBy().getUsername());
		inquiryResponse.setItemId(inquiry.getInquiredItem().getItemId());
		inquiryResponse.setMessage(inquiry.getMessageContent());
		inquiryResponse.setTimeStamp(inquiry.getInquiredTimeStamp());
		inquiryResponse.setInquiryId(inquiry.getInquiryId());
		return inquiryResponse;
	}

	private com.curio.curioapp.curioappbackend.model.User getCurrentlyLoggedInUser() {
		com.curio.curioapp.curioappbackend.model.User user=null;
		User username = authservice.getCurrentUser().orElseThrow(()->
		new IllegalArgumentException("No user logged in"));
		if(username!=null) {
			Optional<com.curio.curioapp.curioappbackend.model.User> optionalUser = userRepository.findByUsername(username.getUsername());
			user= optionalUser.get();
		}
		return user;
	}
	
	private double distance(double longitudeC, double latitudeC, double longitudeP, double latitudeP) {
		longitudeC=Math.toRadians(longitudeC);
		latitudeC=Math.toRadians(latitudeC);
		longitudeP=Math.toRadians(longitudeP);
		latitudeP=Math.toRadians(latitudeP);
		
		double dLongitude=longitudeP-longitudeC;
		double dLatitude=latitudeP-latitudeC;
		
		double a=Math.pow(Math.sin(dLatitude/2),2)+Math.cos(latitudeC)*Math.cos(latitudeP)*Math.pow(Math.sin(dLongitude/2),2 );
		double c=2*Math.asin(Math.sqrt(a));
		double r=6371;
		return (c*r);
		
		
	}
	
	private int calcEditDist(String str1, String str2, int m, int n) {
		if(m==0) {
			return n;
		}
		if(n==0) {
			return m;
		}
		
		if(str1.charAt(m-1)== str2.charAt(n-1)) {
			return calcEditDist(str1,str2,m-1,n-1);
		}
		return 1 + getMin(calcEditDist(str1,str2,m,n-1), calcEditDist(str1,str2,m-1,n), calcEditDist(str1,str2,m-1,n-1));
	}
	
	private int getMin(int a, int b ,int c) {
		if(a<=b && a<=c) {
			return a;
		}
		if(b<=a && b<=c) {
			return b;
		}
		else {
			return c;
		}
	}
}
